#!/usr/bin/env bash

set -euo pipefail

usage() {
  echo "usage: $0 <task-dir>" >&2
  exit 64
}

if [[ $# -ne 1 ]]; then
  usage
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
skill_dir="$(cd "${script_dir}/.." && pwd)"
template="${skill_dir}/templates/task-agents.md"
marker='<!-- herdr-tasks generated file.'

if [[ ! -f "${template}" ]]; then
  echo "template not found: ${template}" >&2
  exit 1
fi

if [[ ! -d "$1" ]]; then
  echo "task directory not found: $1" >&2
  exit 1
fi

task_dir="$(cd "$1" && pwd)"

check_generated() {
  local path="$1"

  if [[ ! -e "${path}" ]]; then
    return 0
  fi

  if [[ -L "${path}" || ! -f "${path}" ]]; then
    echo "conflict: ${path} exists and is not a regular file" >&2
    return 1
  fi

  if [[ "$(head -n 1 "${path}")" != "${marker}"* ]]; then
    echo "conflict: ${path} was not generated by this script" >&2
    return 1
  fi
}

has_conflict=0

check_generated "${task_dir}/AGENTS.md" || has_conflict=1
check_generated "${task_dir}/CLAUDE.md" || has_conflict=1

if [[ ${has_conflict} -ne 0 ]]; then
  echo "aborting without changes because conflicts were found" >&2
  exit 1
fi

agents_md="$(cat "${template}")"
agents_md="${agents_md//@@SKILL_DIR@@/${skill_dir}}"
agents_md="${agents_md//@@TASK_DIR@@/${task_dir}}"

printf '%s\n' "${agents_md}" >"${task_dir}/AGENTS.md"
printf '%s\n\n%s\n' "${marker} AGENTS.md を読み込むためだけのファイルである -->" '@AGENTS.md' \
  >"${task_dir}/CLAUDE.md"

echo "wrote: ${task_dir}/AGENTS.md"
echo "wrote: ${task_dir}/CLAUDE.md"
